# Imports

In [40]:
!pip install pydmd

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 61 kB 3.7 MB/s 
     |████████████████████████████████| 52 kB 1.5 MB/s 


In [41]:
from pathlib import Path
import cv2
import matplotlib.pyplot as plt
import warnings
import pandas as pd
warnings.filterwarnings('ignore')
import numpy as np
from PIL import Image
from PIL import ImageFilter
import os
from pydmd import DMD

%matplotlib inline


# Reading Images

In [1]:
from google.colab import drive
drive.mount('drive')

Mounted at drive


In [3]:
# destination_path = '/content/drive/MyDrive/ML_Term_Project/project_data'
# target_path = '/content/drive/MyDrive/ML_Term_Project/pre_processed'

# format_of_your_images = 'jpg'

# all_the_files = Path(destination_path).rglob(f'*.{format_of_your_images}')

# for f in all_the_files:
#    p = cv2.imread(str(f))
#    #  transformation
#    gray_image = cv2.cvtColor(p, cv2.COLOR_BGR2GRAY)
#    resized = cv2.resize(gray_image, (96,120),interpolation = cv2.INTER_AREA)
#    cv2.imwrite(f'{target_path}/{f.name}', resized)
     

**DOWN SAMPLED GRAY SCALED IMAGES DONE**

In [5]:
# Import the necessary libraries
from PIL import Image
from numpy import asarray
 
 
# load the image and convert into
# numpy array
img = Image.open('/content/drive/MyDrive/ML_Term_Project/pre_processed/in001201.jpg')
 
# asarray() class is used to convert
# PIL images into NumPy arrays
numpydata = asarray(img)
 
# <class 'numpy.ndarray'>
print(type(numpydata))
 
#  shape
print(numpydata.shape)

print(numpydata)

<class 'numpy.ndarray'>
(120, 96)
[[ 45  38  28 ... 125 120 114]
 [ 34  36  48 ... 196 197 197]
 [ 62  44  24 ... 196 194 200]
 ...
 [ 25  11  10 ... 112 129 110]
 [ 20  12  10 ... 115 112 108]
 [ 15  10   9 ... 129 109 107]]


In [6]:
array2 = numpydata.flatten()
#Memory occupied by array 2
print(array2.shape)
#displaying the 1-D array
print(array2)

(11520,)
[ 45  38  28 ... 129 109 107]


In [7]:
array3=array2
print(array3)

[ 45  38  28 ... 129 109 107]


In [11]:
np.c_[array2, array3].shape

(11520, 2)

In [26]:
inPath ="/content/drive/MyDrive/ML_Term_Project/pre_processed"

X = np.zeros(11520) 
# path of the folder that will contain the modified image
#outPath ="E:\\GeeksforGeeks\\images_rotated"
  
for imagePath in os.listdir(inPath):

  inputPath = os.path.join(inPath, imagePath)
  
  # inputPath contains the full directory name
  img = Image.open(inputPath)
  
  #fullOutPath = os.path.join(outPath, 'invert_'+imagePath)
  # fullOutPath contains the path of the output
  # image that needs to be generated

  np_img = asarray(img)
  f_np_img = np_img.flatten()

  X = np.c_[X,f_np_img]

X = X[:,1:]


In [27]:
X.shape

(11520, 30)

In [34]:
df = pd.DataFrame(X)
df.to_csv('/content/drive/MyDrive/ML_Term_Project/snapshots.csv',index=False)

In [35]:
df_f = pd.read_csv('/content/drive/MyDrive/ML_Term_Project/snapshots.csv')
arr = df_f.to_numpy()

In [37]:
arr.shape

(11520, 30)

In [38]:
arr

array([[ 45.,  46.,  45., ...,  39.,  42.,  47.],
       [ 38.,  37.,  36., ...,  35.,  35.,  35.],
       [ 28.,  24.,  25., ...,  26.,  26.,  28.],
       ...,
       [129., 128., 127., ..., 129., 131., 129.],
       [109., 109., 106., ..., 111., 109., 107.],
       [107., 106., 109., ..., 104., 107., 107.]])

# Performing DMD on our X matrix

In [42]:
dmd = DMD(svd_rank=29)
dmd.fit(X)

In [43]:
x = dmd.reconstructed_data
x.shape

(11520, 30)

In [44]:
type(x)

numpy.ndarray

In [46]:
x[0]

array([45.        +7.72073061e-15j, 46.        -1.02197197e-14j,
       45.        -4.63757193e-14j, 41.        +8.88448040e-15j,
       42.        -4.07630671e-14j, 49.        +2.86085401e-15j,
       42.        -3.25290465e-15j, 39.        -1.39243718e-15j,
       42.        -4.30082348e-14j, 49.        -1.50696388e-14j,
       43.        +2.95342676e-14j, 44.        +1.39953947e-14j,
       48.        +3.37314387e-15j, 50.        -1.68870849e-14j,
       38.        -2.10992211e-14j, 47.        -1.20364701e-14j,
       41.        +1.33971818e-14j, 47.        -1.60397053e-14j,
       49.        -2.86909625e-14j, 46.        -2.02854372e-14j,
       43.        +2.43480790e-14j, 49.        -3.16525618e-16j,
       50.        -1.88382443e-14j, 46.        -2.05601078e-14j,
       50.        -1.50521341e-14j, 49.        -1.60597189e-14j,
       47.        +1.02339075e-14j, 39.        -1.92129964e-14j,
       42.        -1.89904662e-14j, 47.19285631-2.07510286e-14j])